<?php /** @var \App\Views\Scripts\index $this */ ?>
<div class="document">
	<h1><?=$this->heading?></h1>

	<br />
	<p><?=$this->description?>, <br />primary platforms: JS/PHP/C#/VB.NET/MySQL/TSQL.</p>
	<br />
	
	<blockquote>
		I love to create unusually specialized tools that make work-life easier for me, 
		people around or people on my IT courses. Experience in IT has taught me, that time is money, 
		therefore it decides about the developer quality, how well he can weigh these two things 
		against his inappropriate precision of source code :-)
	</blockquote>

	<menu>
		<li><a href="<?=$this->Url('cv')?>">
			CV
		</a></li>
		<li><a href="<?=$this->Url('training')?>">
			ICT training
		</a></li>
		<li><a href="<?=$this->Url('projects')?>">
			Open Source
		</a></li>
		<li><a href="<?=$this->Url('contact')?>">
			Contact
		</a></li>
	</menu>

</div>