<?php
	/** @var \App\Views\Layouts\standard $this */
	$homeUrl = $this->Url('home');
?>
<div class="left-panel glass" id="left-panel">
	<div class="roof">
		<a href="#" class="icon icon-close" id="left-panel-close"></a>
		<a href="<?=$homeUrl?>" class="name">
			<strong><?=$this->appName?></strong>
		</a>
		<?=$this->RenderLayout('body/themes')?>
		<strong class="position">
			<?=str_replace("\n", "<br />", $this->Translate('freelance web developer, trainer & consultant'))?>,<br />
			<?=$this->Translate('primary platforms')?>:<br />
			JS/PHP/C#/VB.NET/MySQL/TSQL
		</strong>
	</div>
	<?=$this->navigationMain?>
</div>
<header class="glass">
	<a href="#" class="icon icon-hamburger" id="left-panel-open"></a>
	<a href="<?=$homeUrl?>" class="name">
		<strong><?=$this->appName?></strong>
	</a>
</header>
<?=$this->navigationBreadCrumbs?>
<main class="glass">
	<?=$this->GetContent()?>
</main>
<footer class="glass">
	<?=$this->RenderLayout('footer/navigation-localization')?>
	<?=$this->RenderLayout('footer/navigation-media')?>
	<?=$this->RenderLayout('footer/sources')?>
</footer>