<?php
	/** @var \App\Views\Layouts\standard $this */
?><div class="container">
	<header>
		<div class="glass roof">
			<a href="<?=$this->Url('home')?>" class="name">
				<strong><?=$this->appName?></strong>
			</a>
			<strong class="position">
				<?=$this->Translate('freelance web developer, trainer & consultant')?>,<br />
				<?=$this->Translate('primary platforms')?>: <?=$this->appDesc?>
			</strong>
			<?=$this->RenderLayout('body/themes')?>
		</div>
		<?=$this->navigationMain?>
	</header>
	<main>
		<?=$this->navigationBreadCrumbs?>
		<div class="glass">
			<?=$this->GetContent()?>
		</div>
	</main>
	<footer class="glass">
		<?=$this->RenderLayout('footer/navigation-localization')?>
		<?=$this->RenderLayout('footer/navigation-media')?>
		<?=$this->RenderLayout('footer/sources')?>
	</footer>
</div>