<?php
	/** @var \App\Views\Layouts\standard $this */
	if ($this->isProduction && isset($this->google->analyticsId)): /* Not for development, alpha or beta: */
?><script nonce="<?=$this->nonce?>" async src="https://www.googletagmanager.com/gtag/js?id=<?php echo $this->google->analyticsId; ?>"></script>
<script nonce="<?=$this->nonce?>">
window.dataLayer=window.dataLayer||[];
function gtag(){dataLayer.push(arguments);}
gtag('js',new Date());
gtag('config','<?php echo $this->google->analyticsId; ?>');
</script>
<?php endif; ?>
