<?php
	/**
	 * @var \App\Views\Scripts\front $this
	 */
	$mapCode = '';
	if (isset($this->google->mapsApiKey)) {
		$url = "https://www.google.com/maps/embed/v1/place?" . urldecode(http_build_query([
			'q'		=> str_replace(' ', '+', 'Tom Flídr, Mělčany 65, 664 64, Czech republic'),
			'center'	=> '49.01987842577926, 14.941575873472148',
			'zoom'		=> 7,			// 0 to 21
			'maptype'	=> 'roadmap',	// roadmap (default) or satellite
			'language'	=> $this->langCode,
			'region'	=> $this->countryCode,
			'key'		=> $this->google->mapsApiKey,
		], '', '&amp;'));
		$mapCode = <<<MAPS
<div class="map">
	<iframe
		src="{$url}" 
		frameborder="0" style="border:0;"
		allow="fullscreen" allowfullscreen="true"
		loading="lazy" 
		referrerpolicy="no-referrer-when-downgrade"
	></iframe>
</div>
MAPS;
	}

?><div class="document <?=$this->mediaSiteVersion?>">
	<?=$this->XmlLatte($this->document, [
		'contacts'	=> $this->contacts,
		'map'		=> $mapCode,
	])?>
</div>