<?php
	/**
	 * @var \App\Views\Layouts\standard $this
	 * @var \App\Routers\MediaAndLocalization $router
	 * @var \MvcCore\Request $request
	 */
	$router = $controller->GetRouter();
	$request = $controller->GetRequest();
	$allowedLocalizations = $router->GetAllowedLocalizations();
	$defaultLocalization = $router->GetDefaultLocalization(TRUE);
	$defaultLocalizationIndex = array_search($defaultLocalization, $allowedLocalizations, TRUE);
	if ($defaultLocalizationIndex !== FALSE) unset($allowedLocalizations[$defaultLocalizationIndex]);
	$allowedLocalizations = array_merge([$defaultLocalization], $allowedLocalizations);
	$localizationsCount = count($allowedLocalizations);
	$fullUrl = $request->GetFullUrl();
	$localizationUrlParam = \MvcCore\Ext\Routers\ILocalization::URL_PARAM_LOCALIZATION;

?><div class="document"><?php
	echo '<label>' . __('Language:') . ' </label>';
	foreach ($allowedLocalizations as $index => $allowedLocalization):
		if ($index > 0 && $index < $localizationsCount) 
			echo ', ';
		if ($allowedLocalization == $localization):
			?><span><?=__('Language: ' . $allowedLocalization)?></span><?php
		else:
			?><a href="<?php echo $this->Url(
				'self',
				[$localizationUrlParam  => $allowedLocalization]
			); ?>"><?=__('Language: ' . $allowedLocalization)?></a><?php
		endif;
	endforeach;
?></div>
