<?php
	/**
	 * @var $this  \MvcCore\View
	 * @var $items \App\Models\Navigations\Set
	 */
	$itemsCount = count($items) + 1;
	$colPerc = intval(round(100.0 / ($itemsCount * 1.5)));
	$cssClassesCodes = [];
?>

<table class="main-nav">
	<thead><tr>
		<?php foreach ($items as $key1 => $itemLevel1): ?>
			<th width="<?=$colPerc?>%"<?php
				$cssClasses = [];
				if ($itemLevel1->GetCssClass() !== NULL)
					$cssClasses[] = $itemLevel1->GetCssClass();
				if ($itemLevel1->GetSelected())
					$cssClasses[] = 'selected';
				$cssClassesCode = count($cssClasses) > 0
					? ' class="' . implode(' ', $cssClasses) . '"'
					: '';
				$cssClassesCodes[$key1] = $cssClassesCode;
				echo $cssClassesCode;
			?>>
				<a <?=$cssClassesCode?>href="<?=$itemLevel1->GetUrl()?>">
					<b><?=$itemLevel1->GetTitle()?></b>
					<?php $desc = $itemLevel1->GetDescription(); ?>
					<?php if ($desc !== NULL): ?>
						<span><?=$desc?></span>
					<?php endif ?>
				</a>
			</th>
		<?php endforeach; ?>
	</tr></thead>
	<tbody><tr>
		<?php foreach ($items as $key1 => $itemLevel1): ?>
			<td<?=$cssClassesCodes[$key1]?>>
				<?php foreach ($itemLevel1->GetItems() as $itemLevel2): ?>
					<span<?php
						$cssClasses = [];
						if ($itemLevel2->GetCssClass() !== NULL)
							$cssClasses[] = $itemLevel2->GetCssClass();
						if ($itemLevel2->GetSelected())
							$cssClasses[] = 'selected';
						$cssClassesCode = count($cssClasses) > 0
							? ' class="' . implode(' ', $cssClasses) . '"'
							: '';
						echo $cssClassesCode;
					?>>
						<a <?=$cssClassesCode?>href="<?=$itemLevel2->GetUrl()?>">
							<?=$itemLevel2->GetTitle()?>
						</a>
					</span>
				<?php endforeach; ?>
			</td>
		<?php endforeach; ?>
	</tr></tbody>
</table>