<?php /** @var \App\Views\Scripts\front $this */ ?>
<div class="document">

	<h1><?=$title?></h1>

	<h3 class="indent">Open Source Projects <small>(<a href="https://github.com/tomflidr/" target="_blank">Github</a>)</small></h3>
	<table class="os-projects"><tbody>
		<tr>
			<th>.NET</th>
			<td>
				<a href="https://github.com/debug-sharp" target="_blank">Desharp</a>, 
				<a href="https://github.com/Databasic-NET/Databasic" target="_blank">Databasic.NET</a>,
				<a href="https://github.com/parallel-pooler" target="_blank">Pooler</a>
			</td>
		</tr>
		<tr>
			<th>JS/TS</th>
			<td>
				<a href="https://github.com/ExtTS/generator" target="_blank">Ext.TS</a>, 
				<a href="https://github.com/web-dev-server/web-dev-server" target="_blank">Web&nbsp;Dev&nbsp;Server&nbsp;for&nbsp;Node.JS</a>, 
				<a href="https://github.com/tomFlidr/Notepad-HTML-JS-Formater-Plugin" target="_blank">Notepad++&nbsp;JS/HTML&nbsp;Formatter&nbsp;Plugin</a>,
				<a href="https://github.com/tomFlidr/ajax.js" target="_blank">Ajax.JS</a>,
				<a href="https://github.com/tomFlidr/jDiet.js" target="_blank">jDiet.JS</a>,
				<a href="https://github.com/tomFlidr/gradient-overlay.js" target="_blank">GradientOverlay.JS</a>,
				<a href="https://github.com/tomFlidr/class-advanced.js" target="_blank">ClassAdvanced.JS</a>
			</td>
		</tr>
		<tr>
			<th>PHP</th>
			<td>
				<a href="https://github.com/mvccore/mvccore" target="_blank">MvcCore</a>, 
				<a href="https://github.com/tomFlidr/sreality-configurable-rss" target="_blank">SReality RSS</a>
			</td>
		</tr>
		<tr>
			<th>SQL</th>
			<td>
				<a href="https://bitbucket.org/tomflidr/imdb-training-database/src" target="_blank">IMDB Training Database</a>
			</td>
		</tr>
			
			
	</tbody></table>

</div>