<?php
	/** @var \App\Views\Layouts\standard $this */
?><!DOCTYPE HTML>
<html lang="<?=$this->localization?>">
	<head>
		<?=$this->RenderLayout('head/common-tags')?>
		<?=$this->RenderLayout('head/preloading')?>
		<?=$this->RenderLayout('head/metrics')?>
		<?=$this->Css('headAll')->Render()?>
		<?=$this->Css('headMediaTheme')->Render()?>
		<?=$this->Css('headAllPrint')->Render()?>
		<?=$this->Css('headPage')->Render()?>
		<?=$this->Js('headAll')->Render()?>
		<?=$this->Js('headPage')->Render()?>
	</head>
	<body class="<?=$this->theme->currentDcShort?> <?=$this->theme->currentDcFull?> <?=$this->mediaSiteVersion?>">
		<input type="hidden" id="core-config" value="<?=$this->EscapeAttrJs($this->coreConfig)?>" />
		<?=$this->RenderLayout('./body/old-browser-warning')?>
		<?=$this->RenderLayout('./body/layout.' . $this->mediaSiteVersion)?>
		<script type="text/javascript" nonce="<?$this->$nonce?>">Core.Page.GetPage();</script>
	</body>
</html>
